# Generated by Django 2.0.2 on 2018-05-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
